-- ==============================================================================
-- Supabase Database & Storage Setup Script for Portfolio
-- Run this script in the Supabase SQL Editor (Dashboard -> SQL Editor -> New query)
-- ==============================================================================

-- 1. Create the portfolio_items table
CREATE TABLE IF NOT EXISTS public.portfolio_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    link TEXT NOT NULL,
    category TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for portfolio_items table
-- Anyone can view portfolio items (visitors)
CREATE POLICY "Allow public read-only access on portfolio_items"
    ON public.portfolio_items
    FOR SELECT
    USING (true);

-- Only authenticated users (Admin) can insert, update, or delete items
CREATE POLICY "Allow authenticated users to insert portfolio_items"
    ON public.portfolio_items
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update portfolio_items"
    ON public.portfolio_items
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete portfolio_items"
    ON public.portfolio_items
    FOR DELETE
    TO authenticated
    USING (true);

-- 4. Create public Storage Bucket for portfolio preview images
-- Note: You can also create this bucket manually in Dashboard -> Storage -> New Bucket named 'portfolio' with 'Public' checked.
INSERT INTO storage.buckets (id, name, public)
VALUES ('portfolio', 'portfolio', true)
ON CONFLICT (id) DO NOTHING;

-- 5. Storage RLS Policies
-- Allow anyone to view/download images from the public bucket
CREATE POLICY "Allow public access to portfolio images"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'portfolio');

-- Allow authenticated users (Admin) to upload images
CREATE POLICY "Allow authenticated users to upload portfolio images"
    ON storage.objects
    FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'portfolio');

-- Allow authenticated users (Admin) to update images
CREATE POLICY "Allow authenticated users to update portfolio images"
    ON storage.objects
    FOR UPDATE
    TO authenticated
    WITH CHECK (bucket_id = 'portfolio');

-- Allow authenticated users (Admin) to delete images
CREATE POLICY "Allow authenticated users to delete portfolio images"
    ON storage.objects
    FOR DELETE
    TO authenticated
    USING (bucket_id = 'portfolio');
